### ISSUE TITLE
ansible-lint is unavailable

### ISSUE THREAD

**Issue by Shalucik** [gofrolist/molecule-action#100]
In the latest versions of v2 (since v2.2.25) ansible-lint is nog longer available in the action
because of this our CI action workflow using molecule doesn't work anymore

this seems to be because ansible-lint was removed from the pip lock file in this commit https://github.com/gofrolist/molecule-action/commit/283c8477cef2132142f0694cfc82f2bec8b3ef89

and we can't use an earlier version of this action before ansible-lint was removed since the docker image used by the action is pinned at v2 https://github.com/gofrolist/molecule-action/blob/master/action.yml#L68

**Comment by gofrolist** [comment]
added in this PR #111

**Comment by florianutz** [comment]
ansible-lint is still unavailable in the latest image. it looks like you have not tagged and pushed it as v2

**Comment by gofrolist** [comment]
> ansible-lint is still unavailable in the latest image. it looks like you have not tagged and pushed it as v2

Fixed in v2 tag and v2.2.31
